// <auto-generated />
namespace real_estate_business.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Business_tbl1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Business_tbl1));
        
        string IMigrationMetadata.Id
        {
            get { return "202010221608554_Business_tbl1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
